apiVersion: v1
kind: Service
metadata:
  name: handshake
spec:
  type: NodePort
  clusterIP: 10.152.183.250
  ports:
    - name: tcp-dns
      protocol: TCP
      port: 53
      targetPort: 53
    - name: udp-dns
      protocol: UDP
      port: 53
      targetPort: 53
  selector:
    app: handshake