apiVersion: v1
kind: Service
metadata:
  name: siacdn-viewer
spec:
  type: NodePort
  clusterIP: 10.152.183.252
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: siacdn-viewer