kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: siacdn-viewer-0
spec:
  storageClassName: "microk8s-hostpath"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: siacdn-viewer-1
spec:
  storageClassName: "microk8s-hostpath"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: siacdn-viewer-2
spec:
  storageClassName: "microk8s-hostpath"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: siacdn-viewer-3
spec:
  storageClassName: "microk8s-hostpath"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---