apiVersion: apps/v1
kind: Deployment
metadata:
  name: siacdn-viewer-0
spec:
  selector:
    matchLabels:
      appinstance: siacdn-viewer-0
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: siacdn-viewer
        appinstance: siacdn-viewer-0
    spec:
      nodeName: alpha-ny1
      terminationGracePeriodSeconds: 10
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.152.183.250
      volumes:
      - name: siacdn-viewer-0
        persistentVolumeClaim:
          claimName: siacdn-viewer-0
      containers:
      - name: sia
        image: ericflo/siacdn-viewnode:latest
        imagePullPolicy: Always
        command: ["siad-wrapper.sh"]
        ports:
        - containerPort: 9980
        volumeMounts:
        - name: siacdn-viewer-0
          mountPath: /etc/sia
        envFrom:
        - secretRef:
            name: siacdn-viewer
        readinessProbe:
          exec:
            command:
            - /go/bin/readiness.sh
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 5
        resources:
          requests:
            memory: "2Gi"
            cpu: "250m"
          limits:
            memory: "8Gi"
            cpu: "6500m"
      - name: nginx
        image: ericflo/siacdn-portal:latest
        imagePullPolicy: Always
        command: ["/etc/skynet/start-portal.sh"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: siacdn-viewer-0
          mountPath: /etc/sia
        envFrom:
        - secretRef:
            name: siacdn-viewer
        - configMapRef:
            name: siacdn-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "500Mi"
            cpu: "500m"
      - name: handshake-api
        image: ericflo/siacdn-handshake-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3100
        envFrom:
        - secretRef:
            name: siacdn-handshake
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "500Mi"
            cpu: "500m"
      - name: rclone-backup
        image: ericflo/rclone-backup:latest
        imagePullPolicy: Always
        command: ["rclone-backup", "--source", "/etc/sia"]
        volumeMounts:
        - name: siacdn-viewer-0
          mountPath: /etc/sia
        envFrom:
        - secretRef:
            name: siacdn-backup
        env:
        - name: BACKUP_TARGET
          value: rclone-backups-maxint/siacdn/viewer/0
        - name: RCLONE_MAX_SIZE
          value: 1G